image: docker:stable

build:
  stage: build
  script:
   - docker stop chowdown || true
   - docker rm chowdown || true
   - docker build -t baswag/chowdown .
test:
  stage: test
  script:
   - docker run --name chowdown baswag/chowdown /bin/bash -c "cd /opt/chowdown; jekyll build -d test"
   - docker rm chowdown
  
deploy:
  stage: deploy
  script:
   - docker run --name chowdown -p 4000:4000 --restart always -d baswag/chowdown /bin/bash -c "cd /opt/chowdown; jekyll serve"
