image: docker:stable

build:
  stage: build
  script:
   - docker build -t baswag/chowdown .
test:
  stage: test
  script:
   - docker run baswag/chowdown /bin/bash -c "cd /opt/chowdown; jekyll build -d test"
  
deploy:
  stage: deploy
  script:
   - docker run -p 4000:4000 --restart always -d baswag/chowdown /bin/bash -c "cd /opt/chowdown; jekyll serve"
